// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreatAccount(ctx context.Context, arg CreatAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
